- !host pki-service
- !policy
  id: pki
  owner: !user admin
  body:
  - !webservice
  - !variable ca/cert
  - !variable ca/key
  - !variable ca/cert-chain
  - !variable crl

  - !policy templates
  - !policy certificates
